/// Hive Types
const int HIVE_TYPE_ID_COUNTING_UNIT_BY_ID_VO = 1;
const int HIVE_TYPE_ID_CART_ITEM_VO = 2;
const int HIVE_TYPE_ID_PRE_ORDER_ITEM_VO = 3;
const int HIVE_TYPE_ID_CUSTOM_PRE_ORDER_ITEM_VO = 4;

/// Box Names
const String BOX_NAME_COUNTING_UNIT_BY_ID_VO =
    "BOX_NAME_COUNTING_UNIT_BY_ID_VO";
const String BOX_NAME_CART_ITEM_VO = "BOX_NAME_CART_ITEM_VO";
const String BOX_NAME_PRE_ORDER_ITEM_VO = "BOX_NAME_PRE_ORDER_ITEM_VO";
const String BOX_NAME_CUSTOM_PRE_ORDER_ITEM_VO = "BOX_NAME_CUSTOM_PRE_ORDER_ITEM_VO";
